name: Execução de testes pré-commit frontEnd

on:
  push:
    branches: [main]
    paths:
      - 'frontEnd/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontEnd/**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: frontEnd

      - name: Build
        run: npm run build --if-present
        working-directory: frontEnd

      - name: Executar testes
        run: npm test
        working-directory: frontEnd